name: anthony.fortnite.ca CI/CD Workflow
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}Websites/anthony.fortnite.ca
            git pull
